# Generated by Django 4.1.1 on 2022-10-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='cvr_url',
            new_name='cover_url',
        ),
    ]
